CREATE TABLE city (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(30)  NOT NULL
);

CREATE TABLE restaurant (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    city_id  BIGINT       NOT NULL REFERENCES city (id),
    owner_id BIGINT       NOT NULL REFERENCES app_user (id)
);

CREATE TABLE menu_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id  BIGINT         NOT NULL REFERENCES restaurant (id),
    name           VARCHAR(255)   NOT NULL,
    price          DECIMAL(12, 2) NOT NULL,
    stock_quantity INT            NOT NULL,
    version        INT            NOT NULL DEFAULT 0,
    available      BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE delivery_partner (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL UNIQUE REFERENCES app_user (id),
    availability_status VARCHAR(20) NOT NULL
);

CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT         NOT NULL REFERENCES app_user (id),
    restaurant_id BIGINT         NOT NULL REFERENCES restaurant (id),
    status        VARCHAR(30)    NOT NULL,
    total_amount  DECIMAL(12, 2) NOT NULL,
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP      NOT NULL
);

CREATE TABLE order_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT         NOT NULL REFERENCES orders (id),
    menu_item_id        BIGINT         NOT NULL REFERENCES menu_item (id),
    quantity            INT            NOT NULL,
    price_at_order_time DECIMAL(12, 2) NOT NULL
);

CREATE TABLE payment (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT         NOT NULL UNIQUE REFERENCES orders (id),
    amount   DECIMAL(12, 2) NOT NULL,
    status   VARCHAR(20)    NOT NULL,
    method   VARCHAR(50)    NOT NULL
);

CREATE TABLE delivery_assignment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL UNIQUE REFERENCES orders (id),
    partner_id  BIGINT      REFERENCES delivery_partner (id),
    status      VARCHAR(20) NOT NULL,
    offered_at  TIMESTAMP   NOT NULL,
    accepted_at TIMESTAMP
);

CREATE TABLE rating (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT    NOT NULL UNIQUE REFERENCES orders (id),
    customer_id       BIGINT    NOT NULL REFERENCES app_user (id),
    restaurant_rating INT       NOT NULL,
    partner_rating    INT       NOT NULL,
    comment           VARCHAR(1000),
    created_at        TIMESTAMP NOT NULL
);

CREATE INDEX idx_restaurant_city ON restaurant (city_id);
CREATE INDEX idx_menu_item_restaurant ON menu_item (restaurant_id);
CREATE INDEX idx_order_customer ON orders (customer_id);
CREATE INDEX idx_order_restaurant_status ON orders (restaurant_id, status);
CREATE INDEX idx_order_item_order ON order_item (order_id);
CREATE INDEX idx_delivery_assignment_status ON delivery_assignment (status);
